### ISSUE TITLE
Hidden blueprint unlock: confirmation window shows wrong tech

### ISSUE THREAD

**Issue by SIVLER7405** [PavelZinchenko/event_horizon#19] opened 2022-08-29 07:49 UTC
When destroying an outpost, player unlocks a blueprint, but the game shows next blueprint as unlocked. If unlocked blueprint is the last, it doesn't show anything.
![image](https://user-images.githubusercontent.com/96327594/187151190-c3d0e0dd-9618-4929-9b93-70c0a2c8f066.png)

**Comment by juh9870** [comment] 2022-08-29 20:27
I can't reproduce, does this still happens in opensource version?

**Comment by SIVLER7405** [comment] 2022-08-30 14:50
While in Unity, no, this does not happen. Don't know about build version but I guess it goes the same.

**Comment by juh9870** [comment] 2022-08-30 19:46
Okay, I will close this for now then. If you manage to reproduce it, either reopen this issue or crate a new one

**Closed as completed by juh9870** 2022-08-30 19:46 UTC
Labels: more info needed
